[package]
name = "gitlab-version-bot"
version = "0.1.0"
authors = ["Jean-Philippe Bidegain <jp@bidega.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
